[[main]]
  name = "Home"
  url = ""
  weight = -110

# Submenus are done this way: parent -> identifier
[[main]]
  name = "BlogRolls"
  identifier = "BlogRolls"
  weight = -109
[[main]]
  parent = "BlogRolls"
  name = "General"
  url = "page/blogroll/"
  weight = 1
[[main]]
  parent = "BlogRolls"
  name = "Security"
  url = "page/blogroll-security/"
  weight = 2
[[main]]
  parent = "BlogRolls"
  name = "AI"
  url = "page/blogroll-ai/"
  weight = 3

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Tools"
  weight = -108
[[main]]
  parent = "Tools"
  name = "ðŸ“… Blogs RSS Updates by days"
  url = "https://benoit-gaumard.io/tools/rss-updates-by-days.html"
  target = "_blank"
  weight = 1
[[main]]
  parent = "Tools"
  name = "ðŸ·ï¸ Blogs RSS Updates by categories"
  url = "https://benoit-gaumard.io/tools/rss-updates-by-cats.html"
  target = "_blank"
  weight = 2
[[main]]
  parent = "Tools"
  name = "â° Azure retirements updates"
  url = "https://benoit-gaumard.io/tools/azure-retirements.html"
  target = "_blank"
  weight = 3
[[main]]
  parent = "Tools"
  name = "ðŸ†• All Azure updates"
  url = "https://benoit-gaumard.io/tools/azure-updates-all.html"
  target = "_blank"
  weight = 4

[[main]]
  name = "Latest Azure updates"
  url = "https://benoit-gaumard.io/tools/azure-updates-all.html"
  target = "_blank"
  weight = -107

[[main]]
  name = "Fun Zone"
  url = "page/funzone/"
  weight = -106

  [[main]]
  name = "About Me"
  url = "about/"
  weight = -105

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "Twitter"
#  url = "https://twitter.com/"

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Benoit-Gaumard/"
#[[social]]
#  name = "twitter"
#  weight = 2
#  url = "https://twitter.com/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/benoit-gaumard/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"